version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend_c
    ports:
      - "4000:4000"
    env_file:
      - ./backend/config/config.env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: frontend_c
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always

  admin:
    build:
      context: ./admin
      dockerfile: dockerfile
    container_name: admin_c
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./admin:/app
      - /app/node_modules
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456789"
      POSTGRES_DB: egp_store
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data: