version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: backend_c
    ports:
      - "4000:4000"
    env_file:
      - ./backend/config/config.env
    environment:
      - DB_HOST=db
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://62.72.58.5:4000
    container_name: frontend_c
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

  admin:
    build:
      context: ./admin
      dockerfile: dockerfile
      args:
        - VITE_API_URL=http://62.72.58.5:4000
    container_name: admin_c
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: egp_store
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data: